import doubletdetection
import pandas as pd
import argparse as ap

parser = ap.ArgumentParser(description='Run DoubletDetection')
parser.add_argument('--input', dest='input', help='The input tsv file generated by the pipeline')
parser.add_argument('--output', dest='output', help='The output csv file')
args = parser.parse_args()

dat = pd.read_table(args.input, sep='\t')

clf = doubletdetection.BoostClassifier()
labels = clf.fit(dat).predict()
scores = clf.doublet_score()

to_write = pd.DataFrame({'Barcode':dat.index,'DoubletDetectionScore':scores,'DoubletDetectionLabel':labels})
to_write.to_csv(args.output)
